### PR TITLE
Fix high memory usage by caching gemm workspaces

### LINKED ISSUE #14: Higher Mem usage than original awq?
Hi team, turbomind is an excellent work, following pr in sglang, i'm trying to make this quant method into vllm so i can use awq on V100(sm70).

I've make a runnable version by vllm plugin system, my code can be seen at [turbomind_vllm_plugin](https://github.com/liuyanyi/turbomind_vllm_plugin), but i notice a werid non-torch-memory, here's vllm startup log:

Original AWQ:
```
model weights take 9.09GiB; non_torch_memory takes 0.23GiB; PyTorch activation peak memory takes 4.10GiB; the rest of the memory reserved for KV Cache is 13.55GiB.
```

Turbomind AWQ:
```
model weights take 9.30GiB; non_torch_memory takes 9.17GiB; PyTorch activation peak memory takes 4.09GiB; the rest of the memory reserved for KV Cache is 4.42GiB.
```

Is this as expected? or how can i reduce this usage?

Thanks again for this excellent work.

### PR DESCRIPTION
**Pull request by lvhan028**
Fix #14

### CODE REVIEW

File: src/turbomind/api/python/linear.cc [hunk 1]
```diff
@@ -70,6 +76,12 @@ struct Linear::Impl {
         convert_scales_zeros(workspace, scales, qzeros, input_dims_, output_dims_, group_size_, simt);
 
         check_cuda_error(cudaFree(workspace));
+
+        // try to create a gemm workspace for <device_id, default_stream>
+        //and cache it to `workspace_cache_`
+        int device_id;
+        check_cuda_error(cudaGetDevice(&device_id));
+        (void)getWorkspace(device_id, 0);
```
Comment (lzhangzz) [inline src/turbomind/api/python/linear.cc:84]: Why do we need this?

Comment (lvhan028) [reply src/turbomind/api/python/linear.cc:84]: If the default CUDA stream is used, I guess the forward pass could benefit from pre-creating the workspace.

File: src/turbomind/api/python/linear.cc [hunk 2]
```diff
@@ -274,8 +287,38 @@ struct Linear::Impl {
...
+        // create a new workspace if cache missed
+        // auto workspace = std::make_shared<gemm::Workspace>();
+        auto workspace = std::shared_ptr<gemm::Workspace>(new gemm::Workspace,
+            [](gemm::Workspace* p){
+                cudaFreeAsync(p->barriers, 0);
+                cudaFreeAsync(p->partials, 0);
+            });
+        workspace->barriers_size = gemm::Gemm::kBarriersSize;
+        workspace->partials_size = gemm::Gemm::kPartialsSize;
+        cudaMallocAsync(&workspace->barriers, workspace->barriers_size, stream);
```
Comment (lzhangzz) [inline src/turbomind/api/python/linear.cc:307]: `check_cuda_error` on the allocations to avoid slient OOM.

Comment (lvhan028) [reply src/turbomind/api/python/linear.cc]: Sure, added

File: src/turbomind/api/python/linear.cc [hunk 3]
```diff
@@ -274,8 +287,38 @@ struct Linear::Impl {
...
+        auto it = workspace_cache_.find(key);
+        if (it != workspace_cache_.end()) {
+            return *it->second;
+        }
+
+        // create a new workspace if cache missed
+        // auto workspace = std::make_shared<gemm::Workspace>();
+        auto workspace = std::shared_ptr<gemm::Workspace>(new gemm::Workspace,
+            [](gemm::Workspace* p){
+                cudaFreeAsync(p->barriers, 0);
```
[the remark this answers is not in the document]
Comment (lvhan028) [reply src/turbomind/api/python/linear.cc:306]: Do you mean defining a global function to destroy the `workspace_cache_`

**Review by lzhangzz — APPROVED** [review]
